package com.bsiag.ethereum.fxtradingnetwork.events.account;

import java.math.BigDecimal;
import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.bsiag.ethereum.fxtradingnetwork.events.account.TransactionForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class TransactionFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Amount getAmount() {
    return getFieldByClass(Amount.class);
  }

  public Block getBlock() {
    return getFieldByClass(Block.class);
  }

  public BlockTimestamp getBlockTimestamp() {
    return getFieldByClass(BlockTimestamp.class);
  }

  public Created getCreated() {
    return getFieldByClass(Created.class);
  }

  public Data getData() {
    return getFieldByClass(Data.class);
  }

  public From getFrom() {
    return getFieldByClass(From.class);
  }

  public GasLimit getGasLimit() {
    return getFieldByClass(GasLimit.class);
  }

  public GasPrice getGasPrice() {
    return getFieldByClass(GasPrice.class);
  }

  public GasUsed getGasUsed() {
    return getFieldByClass(GasUsed.class);
  }

  /**
   * access method for property Id.
   */
  public String getId() {
    return getIdProperty().getValue();
  }

  /**
   * access method for property Id.
   */
  public void setId(String id) {
    getIdProperty().setValue(id);
  }

  public IdProperty getIdProperty() {
    return getPropertyByClass(IdProperty.class);
  }

  public Nonce getNonce() {
    return getFieldByClass(Nonce.class);
  }

  public Sent getSent() {
    return getFieldByClass(Sent.class);
  }

  public Status getStatus() {
    return getFieldByClass(Status.class);
  }

  public To getTo() {
    return getFieldByClass(To.class);
  }

  public TxFee getTxFee() {
    return getFieldByClass(TxFee.class);
  }

  public TxHash getTxHash() {
    return getFieldByClass(TxHash.class);
  }

  public static class Amount extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class Block extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class BlockTimestamp extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Created extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class Data extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class From extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class GasLimit extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class GasPrice extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class GasUsed extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class IdProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Nonce extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class Sent extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class Status extends AbstractValueFieldData<Integer> {

    private static final long serialVersionUID = 1L;
  }

  public static class To extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class TxFee extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class TxHash extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
