package org.eclipse.scout.tradingnetwork.shared.ethereum;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.tradingnetwork.client.ethereum.AccountForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AccountFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Address getAddress() {
    return getFieldByClass(Address.class);
  }

  public FileContent getFileContent() {
    return getFieldByClass(FileContent.class);
  }

  public FilePath getFilePath() {
    return getFieldByClass(FilePath.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public Password getPassword() {
    return getFieldByClass(Password.class);
  }

  public PasswordVisible getPasswordVisible() {
    return getFieldByClass(PasswordVisible.class);
  }

  public Person getPerson() {
    return getFieldByClass(Person.class);
  }

  public static class Address extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class FileContent extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class FilePath extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Password extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class PasswordVisible extends AbstractValueFieldData<Boolean> {

    private static final long serialVersionUID = 1L;
  }

  public static class Person extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
