package com.bsiag.ethereum.fxtradingnetwork.events.shared.person;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.extension.Extends;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

import com.bsiag.ethereum.fxtradingnetwork.shared.person.PersonFormData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(PersonFormData.class)
@Generated(value = "com.bsiag.ethereum.fxtradingnetwork.events.client.person.PersonFormWalletTabExtension", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PersonFormWalletTabExtensionData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public ShowPassword getShowPassword() {
    return getFieldByClass(ShowPassword.class);
  }

  public WalletAddress getWalletAddress() {
    return getFieldByClass(WalletAddress.class);
  }

  public WalletPassword getWalletPassword() {
    return getFieldByClass(WalletPassword.class);
  }

  public WalletPath getWalletPath() {
    return getFieldByClass(WalletPath.class);
  }

  public static class ShowPassword extends AbstractValueFieldData<Boolean> {

    private static final long serialVersionUID = 1L;
  }

  public static class WalletAddress extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class WalletPassword extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class WalletPath extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
