package com.bsiag.ethereum.fxtradingnetwork.events.shared.event;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.bsiag.ethereum.fxtradingnetwork.events.client.event.DealForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class DealFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  /**
   * access method for property DealId.
   */
  public String getDealId() {
    return getDealIdProperty().getValue();
  }

  /**
   * access method for property DealId.
   */
  public void setDealId(String dealId) {
    getDealIdProperty().setValue(dealId);
  }

  public DealIdProperty getDealIdProperty() {
    return getPropertyByClass(DealIdProperty.class);
  }

  /**
   * access method for property DealNr.
   */
  public String getDealNr() {
    return getDealNrProperty().getValue();
  }

  /**
   * access method for property DealNr.
   */
  public void setDealNr(String dealNr) {
    getDealNrProperty().setValue(dealNr);
  }

  public DealNrProperty getDealNrProperty() {
    return getPropertyByClass(DealNrProperty.class);
  }

  public ExchangeRate getExchangeRate() {
    return getFieldByClass(ExchangeRate.class);
  }

  public OrderBookType getOrderBookType() {
    return getFieldByClass(OrderBookType.class);
  }

  /**
   * access method for property OrganizationId.
   */
  public String getOrganizationId() {
    return getOrganizationIdProperty().getValue();
  }

  /**
   * access method for property OrganizationId.
   */
  public void setOrganizationId(String organizationId) {
    getOrganizationIdProperty().setValue(organizationId);
  }

  public OrganizationIdProperty getOrganizationIdProperty() {
    return getPropertyByClass(OrganizationIdProperty.class);
  }

  public Quantity getQuantity() {
    return getFieldByClass(Quantity.class);
  }

  /**
   * access method for property Status.
   */
  public String getStatus() {
    return getStatusProperty().getValue();
  }

  /**
   * access method for property Status.
   */
  public void setStatus(String status) {
    getStatusProperty().setValue(status);
  }

  public StatusProperty getStatusProperty() {
    return getPropertyByClass(StatusProperty.class);
  }

  public TradingActionBox getTradingActionBox() {
    return getFieldByClass(TradingActionBox.class);
  }

  public static class DealIdProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class DealNrProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class ExchangeRate extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class OrderBookType extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class OrganizationIdProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Quantity extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class StatusProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class TradingActionBox extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
