package com.bsiag.ethereum.fxtradingnetwork.events.shared.event;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.bsiag.ethereum.fxtradingnetwork.events.client.event.DealsTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class DealsTablePageData extends AbstractDealsTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public DealsTableRowData addRow() {
    return (DealsTableRowData) super.addRow();
  }

  @Override
  public DealsTableRowData addRow(int rowState) {
    return (DealsTableRowData) super.addRow(rowState);
  }

  @Override
  public DealsTableRowData createRow() {
    return new DealsTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return DealsTableRowData.class;
  }

  @Override
  public DealsTableRowData[] getRows() {
    return (DealsTableRowData[]) super.getRows();
  }

  @Override
  public DealsTableRowData rowAt(int index) {
    return (DealsTableRowData) super.rowAt(index);
  }

  public void setRows(DealsTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class DealsTableRowData extends AbstractDealsTableRowData {

    private static final long serialVersionUID = 1L;
  }
}
