FROM tomcat:jre8
MAINTAINER BSI-Business-Systems-Integration-AG

ADD org.eclipse.scout.tradingnetwork.all.app.dev-6.0.200-SNAPSHOT.war /usr/local/tomcat/webapps/fxtradingnetwork.war

CMD ["catalina.sh", "run"]